### ISSUE TITLE
To have more than one app using strava_flutter in the same phone

### ISSUE THREAD

**Issue by Laebrye** [dreampowder/strava_flutter#44] opened 2020-09-12 12:52 UTC
We've been developing an app that integrates user Strava data. For development & testing purposes we've set up a couple of flavours.

When performing oauth on any of these flavours, the web page opened up for oauth is inconsistent, but more troubling is that the when selecting `Authorize` on the strava authorization page, navigation back to the correct app doesn't always happen:

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-11 at 14 45 43](https://user-images.githubusercontent.com/34944216/92995210-4df29900-f4f9-11ea-9328-986163ea030c.png)

As you can see in the screenshot, the flavour that the auth screen has been navigated from is the production flavour of the app, but iOS is trying to open this in the staging flavour. This results in our production flavour hanging because it never receives the result of the oauth. It's not consistent either - sometimes the cancelling the auth and hot restarting the app gets the correct flavour, sometimes it doesn't.

Each of the flavours has its own OS app ID extension and Strava client ID/secret. Each of these are held in our secret file and passed to an app config on launch that is then used for initialising Strava objects and performing oauth throughout the app.

I have run `flutter clean` and restarted the simulator between each run and this still happens.

This issue is also present on Android, but not as critical as Android presents alternative apps to the user for opening (so the other flavours can be selected if the wrong one is suggested).

I'm guessing that something has to be done with the URL schemes in the info.plist file but I'm at a loss as to what needs to be done. Any help would be much appreciated

**Comment by BirdyF** [comment] 2020-09-13 12:54
Hi @Laebrye 

What you mean is that you have 2 apps (let say A and B) in your phone using strava_flutter package and that you have trouble after the authentication to get back to the right app?
For instance, you are in app A, call strava_flutter Authentication and are back after the authentication to App B.

If it is the case, I think the problem is coming from info.plist (same thing in Android for AndroidManifest.xml) 
Because of the line below the 2 apps will be listening to the same deep links 
<string>stravaflutter</string>

So what I recommend is that you change the line above in info.plist for instance with 
<string>stravaflutterstaging</string> 
for your staging app.

And then you have to fork strava_flutter to replace in oauth.dart  line 164
   if (uri.scheme.compareTo('stravaflutter') != 0) {
with 
   if ((uri.scheme.compareTo('stravaflutter') != 0) ||   (uri.scheme.compareTo('stravaflutterstaging') != 0) ) {

Let me know if it works.

**Comment by BirdyF** [comment] 2020-09-14 10:24
Sorry @Laebrye but I dont have the time to test for the moment.
Let me know if the modifications that you have done in oauth.dart solved your problem.
If yes I will update  the readme

**Comment by Laebrye** [comment] 2020-09-14 10:27
Will do. I've made some modifications and will run tests today. Apologies for not replying sooner. Really appreciate you helping me out 👍

**Comment by Laebrye** [comment] 2020-09-15 14:48
So we came up with a solution, that (for brevity's sake) took the Url scheme and appended the strava client id to it the stravaflutter value. Then, in Oauth.dart we made two changes:

line 164 as suggested:
```
        if (uri.scheme.compareTo('stravaflutter$clientID') != 0) {
          globals.displayInfo('This is not the good scheme ${uri.scheme}');
        }
```

and on lines 105-108:
```
    } else {
      redirectUrl =
          redirectUrlMobilePrefix + clientID + redirectUrlMobileSuffix;
    }
```

with the `redirectUrlMobile` in constants.dart refactored into a prefix and suffix:
```
final String redirectUrlMobilePrefix =
    // "strava://redirect/"; // To use with iOS or Android
    "stravaflutter"; // To use with iOS or Android
final String redirectUrlMobileSuffix = "://redirect/";
```

I appreciate not everyone will want their clientID exposed in this way (I know it gets printed to the log anyway, but still). It might also be too rigid an approach, hence why I didn't raise a PR for it. A better mechanism might be to add an optional redirectUrlId argument to the oauth method, and update the documentation to specify to developers that the `straveflutter` values in AndroidManifest.xml and Info.plist files be suffixed with an appropriate ID.

I'd be keen to know your thoughts and would be happy to make the changes and raise a PR

Thanks again for your help.

**Comment by BirdyF** [comment] 2020-09-19 08:17
Hi @Laebrye 

Thanks for the proposal. I am not sure many people will be interested by this PR.
One question : What could be the risk to expose the ClientID?

**Comment by Laebrye** [comment] 2020-09-19 08:50
Well, I assumed that because it's put into the `secret.dart` file that it should be kept secure, but as a colleague of mine has pointed out the client ID is actually available in the URL anyway.

I like the change, but I accept that it's a breaking change.

If you like, I can investigate a way to make the change non-breaking or I'm happy to create a PR for it anyway, even if it's just for you to inspect and reject.

**Comment by BirdyF** [comment] 2020-09-20 12:36
Hi @Laebrye 

Thanks for contributing.
I see that for the moment I will leave it as it is. 
And will modify the title of this issue to help others to find the solution you found.

**Closed** 2021-09-11 14:41 UTC
